import Head from 'next/head'
import Product from '../components/Product'
export default function Home({products}) {
  return (
    <div >
      <Head>
        <title>Home | the best ecommerce website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        {
          products.map(product => <Product key={product.id} product={product}/>)
        }
      </main>
    </div>
  )
}


export const getStaticProps = async () => {
  const res = await fetch('https://fakestoreapi.com/products?_limit=18')
  const data = await res.json()

  return {
      props: {
          products: data
      }
  }
}
